#!/usr/bin/env python3
"""
Compose all four Nature-quality figures into a single trimmed multi-page PDF.

Inputs (already generated by create_nature_quality_figures_real.py):
 - output/NATURE_REAL_figure1_exploration_exploitation.png
 - output/NATURE_REAL_figure2_phase_coherence.png
 - output/NATURE_REAL_figure3_meg_correlations.png
 - output/NATURE_REAL_figure4_comprehensive.png

Output:
 - output/NATURE_REAL_all_figures.pdf (multi-page, each page trimmed to content with small padding)

Notes:
 - Trimming is performed on PNGs, then the trimmed images are embedded as a multi-page PDF.
 - This preserves consistent styling (Arial, sizes, color palette) already set by setup_nature_style().
"""

from pathlib import Path
from typing import List

from PIL import Image, ImageChops


def trim_image_with_padding(img: Image.Image, pad: int = 12) -> Image.Image:
    """Trim white margins from an image and add a uniform padding."""
    rgb = img.convert("RGB")
    bg = Image.new("RGB", rgb.size, (255, 255, 255))
    diff = ImageChops.difference(rgb, bg)
    bbox = diff.getbbox()
    if not bbox:
        return img
    left = max(bbox[0] - pad, 0)
    upper = max(bbox[1] - pad, 0)
    right = min(bbox[2] + pad, img.width)
    lower = min(bbox[3] + pad, img.height)
    return rgb.crop((left, upper, right, lower))


def load_and_trim(paths: List[Path]) -> List[Image.Image]:
    trimmed = []
    for p in paths:
        if not p.exists():
            raise FileNotFoundError(f"Missing figure: {p}")
        im = Image.open(p)
        trimmed.append(trim_image_with_padding(im, pad=12))
    return trimmed


def save_multi_page_pdf(images: List[Image.Image], out_pdf: Path) -> None:
    out_pdf.parent.mkdir(parents=True, exist_ok=True)
    # Ensure all pages are RGB
    rgb_pages = [img.convert("RGB") for img in images]
    rgb_pages[0].save(out_pdf, save_all=True, append_images=rgb_pages[1:])


def main():
    root = Path(__file__).parent
    out_dir = root / "output"
    figure_paths = [
        out_dir / "NATURE_REAL_figure1_exploration_exploitation.png",
        out_dir / "NATURE_REAL_figure2_phase_coherence.png",
        out_dir / "NATURE_REAL_figure3_meg_correlations.png",
        out_dir / "NATURE_REAL_figure4_comprehensive.png",
    ]

    trimmed_images = load_and_trim(figure_paths)
    out_pdf = out_dir / "NATURE_REAL_all_figures.pdf"
    save_multi_page_pdf(trimmed_images, out_pdf)
    print(f"✅ Composed multi-page PDF: {out_pdf}")


if __name__ == "__main__":
    main()



